-- CREATE DATABASE

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- MASOBHYT is unique
ALTER TABLE BENH_NHI
ADD CONSTRAINT unique_masobhyt UNIQUE (MASOBHYT);


CREATE TABLE BENH_NHI (
    MASO UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    HOTEN VARCHAR(255),
    NGAYSINH DATE,
    GIOITINH CHAR(255),
    CHIEUCAO INT NOT NULL,
    CANNANG INT NOT NULL,
    BMI DECIMAL(4, 2),
    TIENSUBENH VARCHAR(555),
    MASOBHYT VARCHAR(255)
);

CREATE TABLE PHU_HUYNH (
    CCCD VARCHAR(100) PRIMARY KEY,
    HOTEN VARCHAR(100) NOT NULL,
    SDT VARCHAR(15) NOT NULL,
    SONHA VARCHAR(100),
    TENDUONG VARCHAR(100),
    PHUONG VARCHAR(50),
    HUYEN VARCHAR(50)  NOT NULL,
    TINH VARCHAR(50) NOT NULL
);

CREATE TABLE GIAM_HO (
    MASO_BN UUID,
    CCCD VARCHAR(100),
    QUANHE VARCHAR(50),
    PRIMARY KEY (MASO_BN, CCCD),
    FOREIGN KEY (MASO_BN) REFERENCES BENH_NHI(MASO),
    FOREIGN KEY (CCCD) REFERENCES PHU_HUYNH(CCCD)
);

CREATE TABLE NHAN_VIEN (
    CCCD VARCHAR(100) PRIMARY KEY,
    HOTEN VARCHAR(100) NOT NULL,
    SDT VARCHAR(15) NOT NULL,
    SONHA VARCHAR(100),
    TENDUONG VARCHAR(100),
    PHUONG VARCHAR(100),
    HUYEN VARCHAR(100) NOT NULL,
    TINH VARCHAR(100) NOT NULL
);

CREATE TABLE NHAN_VIEN_Y_TE (
    CCCD VARCHAR(100) PRIMARY KEY REFERENCES NHAN_VIEN(CCCD)
);

CREATE TABLE BAC_SI (
    CCCD VARCHAR(100) PRIMARY KEY REFERENCES NHAN_VIEN_Y_TE(CCCD),
    CHUYENKHOA VARCHAR(100),
    BANGCAP VARCHAR(100),
    CC_HANHNGHE VARCHAR(100)
)

CREATE TABLE KY_THUAT_VIEN (
    CCCD VARCHAR(100) PRIMARY KEY REFERENCES NHAN_VIEN_Y_TE(CCCD),
    VITRI VARCHAR(100),
    CHUNGCHI VARCHAR(100)
);

CREATE TABLE THU_NGAN (
    CCCD VARCHAR(100) PRIMARY KEY REFERENCES NHAN_VIEN(CCCD)
);


ALTER TABLE BUOI_KHAM_BENH
DROP CONSTRAINT fk_cccd_bs;

ALTER TABLE BUOI_KHAM_BENH
ADD CONSTRAINT fk_cccd_bs FOREIGN KEY (CCCD_BS) REFERENCES BAC_SI(CCCD);

ALTER TABLE BUOI_KHAM_BENH
ADD COLUMN MAHOADON UUID;
ADD CONSTRAINT fk_mahoadon FOREIGN KEY (MAHOADON) REFERENCES HOA_DON(MAHOADON);

CREATE TABLE BUOI_KHAM_BENH (
    MASO UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    NGAYKHAM DATE DEFAULT CURRENT_DATE,
    TAIKHAM BOOLEAN NOT NULL,
    TRANGTHAI VARCHAR(50) NOT NULL,
    HUYETAP VARCHAR(20) NOT NULL,
    NHIETDO DECIMAL(4, 2) NOT NULL,
    CHANDOAN VARCHAR(255) NOT NULL,
    KETLUAN VARCHAR(255) NOT NULL,
    MASO_BN UUID NOT NULL,
    CCCD_BS VARCHAR(100) NOT NULL,
    FOREIGN KEY (MASO_BN) REFERENCES BENH_NHI(MASO),
    FOREIGN KEY (CCCD_BS) REFERENCES BAC_SI(CCCD),
);

CREATE TABLE TRIEU_CHUNG (
    MASO_BKB UUID,
    TRIEUCHUNG VARCHAR(255),
    PRIMARY KEY (MASO_BKB, TRIEUCHUNG),
    FOREIGN KEY (MASO_BKB) REFERENCES BUOI_KHAM_BENH(MASO)
);

drop TABLE hoa_don
CREATE TABLE HOA_DON (
    MAHOADON UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    NGAYTAO DATE DEFAULT CURRENT_DATE,
    TONGTIEN BIGINT NOT NULL,
    GHICHU VARCHAR(500),
    MASO_BKB UUID NOT NULL,
    FOREIGN KEY (MASO_BKB) REFERENCES BUOI_KHAM_BENH(MASO)
    CCCD_PH VARCHAR(100) REFERENCES PHU_HUYNH(CCCD),
    CCCD_TN VARCHAR(100) REFERENCES THU_NGAN(CCCD)
);

CREATE TABLE DICH_VU_KHAM (
    MADICHVU UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    TEN VARCHAR(100) NOT NULL,
    GIACA BIGINT NOT NULL,
    MOTA VARCHAR(500) NOT NULL
);

CREATE TABLE THUOC (
    MASO UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    TEN VARCHAR(100) NOT NULL, 
    DANG VARCHAR(50) NOT NULL,
    GIACA BIGINT NOT NULL
);


CREATE TABLE DON_THUOC (
    MASO_BKB UUID NOT NULL,
    THOIGIANRADON DATE DEFAULT CURRENT_DATE ,
    NGAYTAIKHAM DATE ,
    LOIDAN VARCHAR(255) NOT NULL,
    MASO_BN UUID,
    CCCD_BS VARCHAR(100),
    PRIMARY KEY (MASO_BKB, THOIGIANRADON),
    FOREIGN KEY (MASO_BKB) REFERENCES BUOI_KHAM_BENH(MASO),
    FOREIGN KEY (CCCD_BS) REFERENCES PHU_HUYNH(CCCD),
)

CREATE TABLE SO_LUONG_THUOC (
    MASO_BKB UUID,
    MASO_TH UUID,
    SOLUONG INT NOT NULL,
    CACHSD VARCHAR(255) NOT NULL,
    PRIMARY KEY (MASO_BKB, MASO_TH),
    FOREIGN KEY (MASO_BKB) REFERENCES BUOI_KHAM_BENH(MASO),
    FOREIGN KEY (MASO_TH) REFERENCES THUOC(MASO)
)

ALTER TABLE LAN_THUC_HIEN_DICH_VU
DROP COLUMN MAHOADON;

CREATE TABLE LAN_THUC_HIEN_DICH_VU (
    MASO UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    NGAYTHUCHIEN DATE DEFAULT CURRENT_DATE,
    CHUANDOAN VARCHAR(255) NOT NULL,
    KETLUAN VARCHAR(255) NOT NULL,
    MASO_BKB UUID NOT NULL,
    MAHOADON UUID  NOT NULL,
    MADICHVU UUID DEFAULT uuid_generate_v4(),
    FOREIGN KEY (MASO_BKB) REFERENCES BUOI_KHAM_BENH(MASO),
    FOREIGN KEY (MAHOADON) REFERENCES HOA_DON(MAHOADON),
    FOREIGN KEY (MADICHVU) REFERENCES DICH_VU_KHAM(MADICHVU)
);

CREATE TABLE THAM_GIA_DICH_VU (
    MASO_LTHDV UUID,
    CCCD_NVYT VARCHAR(100),
    PRIMARY KEY (MASO_LTHDV, CCCD_NVYT),
    FOREIGN KEY (MASO_LTHDV) REFERENCES LAN_THUC_HIEN_DICH_VU(MASO),
    FOREIGN KEY (CCCD_NVYT) REFERENCES NHAN_VIEN(CCCD)
);


