CREATE TABLE BENH_NHI (
    MASO UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    HOTEN VARCHAR(255),
    NGAYSINH DATE NOT NULL CHECK (NGAYSINH < CURRENT_DATE),
    GIOITINH CHAR(255) CHECK (GIOITINH IN ('Nam', 'Nữ')),
    CHIEUCAO INT NOT NULL CHECK (CHIEUCAO > 0),
    CANNANG INT NOT NULL CHECK (CANNANG > 0),
    BMI DECIMAL(4, 2) ,
    TIENSUBENH VARCHAR(555),
    MASOBHYT VARCHAR(255) UNIQUE
);


CREATE TABLE PHU_HUYNH (
    CCCD VARCHAR(100) PRIMARY KEY CHECK (LENGTH(CCCD) = 12),
    HOTEN VARCHAR(100) NOT NULL,
    SDT VARCHAR(15) NOT NULL CHECK (LENGTH(SDT) = 10),
    SONHA VARCHAR(100),
    TENDUONG VARCHAR(100),
    PHUONG VARCHAR(50),
    HUYEN VARCHAR(50)  NOT NULL,
    TINH VARCHAR(50) NOT NULL
);


CREATE TABLE GIAM_HO (
    MASO_BN UUID NOT NULL,
    CCCD VARCHAR(100) NOT NULL,
    QUANHE VARCHAR(50) NOT NULL CHECK (QUANHE IN ('Cha', 'Mẹ', 'Anh', 'Chị', 'Em','Bác', 'Dì', 'Chú', 'Cô', 'Ông', 'Bà')),
    PRIMARY KEY (MASO_BN, CCCD),
    FOREIGN KEY (MASO_BN) REFERENCES BENH_NHI(MASO),
    FOREIGN KEY (CCCD) REFERENCES PHU_HUYNH(CCCD)
);


CREATE TABLE NHAN_VIEN (
    CCCD VARCHAR(100) PRIMARY KEY CHECK (LENGTH(CCCD) = 12),
    HOTEN VARCHAR(100) NOT NULL,
    SDT VARCHAR(15) NOT NULL CHECK (LENGTH(SDT) = 10),
    SONHA VARCHAR(100),
    TENDUONG VARCHAR(100),
    PHUONG VARCHAR(100),
    HUYEN VARCHAR(100) NOT NULL,
    TINH VARCHAR(100) NOT NULL
);


CREATE TABLE NHAN_VIEN_Y_TE (
    CCCD VARCHAR(100) PRIMARY KEY REFERENCES NHAN_VIEN(CCCD)
);


CREATE TABLE BAC_SI (
    CCCD VARCHAR(100) PRIMARY KEY REFERENCES NHAN_VIEN_Y_TE(CCCD),
    CHUYENKHOA VARCHAR(100),
    BANGCAP VARCHAR(100),
    CC_HANHNGHE VARCHAR(100)
)


CREATE TABLE KY_THUAT_VIEN (
    CCCD VARCHAR(100) PRIMARY KEY REFERENCES NHAN_VIEN_Y_TE(CCCD),
    VITRI VARCHAR(100),
    CHUNGCHI VARCHAR(100)
);


CREATE TABLE THU_NGAN (
    CCCD VARCHAR(100) PRIMARY KEY REFERENCES NHAN_VIEN(CCCD)
);


CREATE TABLE BUOI_KHAM_BENH (
    MASO UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    NGAYKHAM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TAIKHAM BOOLEAN NOT NULL,
    TRANGTHAI VARCHAR(50) NOT NULL,
    HUYETAP VARCHAR(20) NOT NULL,
    NHIETDO DECIMAL(4, 2) NOT NULL CHECK (NHIETDO > 0),
    CHANDOAN VARCHAR(255) NOT NULL,
    KETLUAN VARCHAR(255) NOT NULL,
    MASO_BN UUID NOT NULL,
    CCCD_BS VARCHAR(100) NOT NULL,
    FOREIGN KEY (MASO_BN) REFERENCES BENH_NHI(MASO),
    FOREIGN KEY (CCCD_BS) REFERENCES BAC_SI(CCCD)
);


CREATE TABLE TRIEU_CHUNG (
    MASO_BKB UUID,
    TRIEUCHUNG VARCHAR(255),
    PRIMARY KEY (MASO_BKB, TRIEUCHUNG),
    FOREIGN KEY (MASO_BKB) REFERENCES BUOI_KHAM_BENH(MASO)
);


CREATE TABLE HOA_DON (
    MAHOADON UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    NGAYTAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TONGTIEN BIGINT NOT NULL CHECK (TONGTIEN >= 0),
    GHICHU VARCHAR(500),
    MASO_BKB UUID NOT NULL,
    CCCD_PH VARCHAR(100) NOT NULL,
    CCCD_TN VARCHAR(100) NOT NULL,
 
    FOREIGN KEY (MASO_BKB) REFERENCES BUOI_KHAM_BENH(MASO),
    FOREIGN KEY (CCCD_PH) REFERENCES PHU_HUYNH(CCCD),
    FOREIGN KEY (CCCD_TN) REFERENCES THU_NGAN(CCCD)
);


CREATE TABLE DICH_VU_KHAM (
    MADICHVU UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    TEN VARCHAR(100) NOT NULL,
    GIACA BIGINT NOT NULL CHECK (GIACA >= 0),
    MOTA VARCHAR(500) NOT NULL
);


CREATE TABLE THUOC (
    MASO UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    TEN VARCHAR(100) NOT NULL,
    DANG VARCHAR(50) NOT NULL CHECK (DANG IN ('Viên', 'Chai', 'Hộp', 'Ống', 'Lọ', 'Gói', 'Hủ', 'Túi','Vỉ', 'Khác')),
    GIACA BIGINT NOT NULL CHECK (GIACA >= 0)
);




CREATE TABLE DON_THUOC (
    MASO_BKB UUID NOT NULL,
    THOIGIANRADON TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NGAYTAIKHAM DATE CHECK (NGAYTAIKHAM > CURRENT_DATE + 3),
    LOIDAN VARCHAR(255) NOT NULL,
    MASO_BN UUID,
    CCCD_BS VARCHAR(100),
    PRIMARY KEY (MASO_BKB, THOIGIANRADON),
    FOREIGN KEY (MASO_BKB) REFERENCES BUOI_KHAM_BENH(MASO),
    FOREIGN KEY (CCCD_BS) REFERENCES BAC_SI(CCCD)
)


CREATE TABLE SO_LUONG_THUOC (
    MASO_BKB UUID,
    MASO_TH UUID,
    SOLUONG INT NOT NULL CHECK (SOLUONG > 0),
    CACHSD VARCHAR(255) NOT NULL,
    PRIMARY KEY (MASO_BKB, MASO_TH),
    FOREIGN KEY (MASO_BKB) REFERENCES BUOI_KHAM_BENH(MASO),
    FOREIGN KEY (MASO_TH) REFERENCES THUOC(MASO)
)




CREATE TABLE LAN_THUC_HIEN_DICH_VU (
    MASO UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    NGAYTHUCHIEN DATE DEFAULT CURRENT_DATE,
    CHUANDOAN VARCHAR(255) NOT NULL,
    KETLUAN VARCHAR(255) NOT NULL,
    MASO_BKB UUID NOT NULL,
    CCCD_NVYT VARCHAR(100)  NOT NULL,
    MADICHVU UUID NOT NULL,
    FOREIGN KEY (MASO_BKB) REFERENCES BUOI_KHAM_BENH(MASO),
    FOREIGN KEY (MADICHVU) REFERENCES DICH_VU_KHAM(MADICHVU),
    FOREIGN KEY (CCCD_NVYT) REFERENCES NHAN_VIEN_Y_TE(CCCD)
);

